control:
  system:
    floorNum: 11
    elevatorNum: 3
    properties:
      upCost: 0.6
      ratio: 0.5
logging:
  level:
    eivense.elevator.service.impl: debug
    eivense.elevator.entity.elevator: debug


